[package]
name = "rust-gpu-tron"
version = "0.1.0"
edition = "2021"

[dependencies]
metal = "0.28"
hex = "0.4"
sha2 = "0.10"
sha3 = "0.10"
rand = "0.8"
bs58 = "0.5"
tiny-keccak = { version = "2.0", features = ["keccak"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1