[package]
name = "create2-benchmark"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[dependencies]
sha3 = "0.10"
hex = "0.4"
lazy_static = "1.4"
once_cell = "1.19"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"